// // dummy.js (or dummy.jsx)
// export default [
//   {
//     id: 1,
//     postedOn: '2025-01-28',
//     title: 'iOS Developer',
//     company: 'Apple',
//     type: 'Full Time',
//     experience: 'Mid Level',
//     location: 'Remote',
//     skills: ['SwiftUI', 'UiKit', 'Core Data'],
//     job_link: 'https://www.apple.com/careers/in/',
//   },
//   {
//     id: 2,
//     postedOn: '2025-02-24',
//     title: 'Frontend Developer',
//     type: 'Full time',
//     location: 'In-office',
//     experience: 'Fresher',
//     company: 'Amazon',
//     skills: ['JavaScript', 'Next.js', 'Tailwind CSS'],
//     job_link: 'https://www.amazon.jobs/en/',
//   },
//   {
//     id: 3,
//     postedOn: '2025-03-02',
//     title: 'Android Developer',
//     type: 'Part time',
//     location: 'Remote',
//     experience: 'Senior Level',
//     company: 'Facebook',
//     skills: ['Kotlin', 'MVVM'],
//     job_link: 'https://facebook.com/careers',
//   },
//   {
//     id: 4,
//     postedOn: '2025-04-01',
//     title: 'Developer Advocate',
//     type: 'Contract',
//     location: 'Hybrid',
//     experience: 'Junior Level',
//     company: 'Netflix',
//     skills: ['web3', 'Content Creation', 'Community'],
//     job_link: 'https://jobs.netflix.com/',
//   },
// ];


// dummy.jsx
export default [
    {

            id: 1,
    postedOn: '2025-01-28',
    title: 'iOS Developer',
    company: 'Apple',
    type: 'Full Time',
    experience: 'Mid Level',
    location: 'Remote',
    skills: ['SwiftUI', 'UiKit', 'Core Data'],
    job_link: 'https://www.apple.com/careers/in/',
  },
  {
    id: 2,
    postedOn: '2025-02-24',
    title: 'Frontend Developer',
    type: 'Full time',
    location: 'In-office',
    experience: 'Fresher',
    company: 'Amazon',
    skills: ['JavaScript', 'Next.js', 'Tailwind CSS'],
    job_link: 'https://www.amazon.jobs/en/',
  },
  {
    id: 3,
    postedOn: '2025-03-02',
    title: 'Android Developer',
    type: 'Part time',
    location: 'Remote',
    experience: 'Senior Level',
    company: 'Facebook',
    skills: ['Kotlin', 'MVVM'],
    job_link: 'https://facebook.com/careers',
  },
  {
    id: 4,
    postedOn: '2025-04-01',
    title: 'Developer Advocate',
    type: 'Contract',
    location: 'Hybrid',
    experience: 'Junior Level',
    company: 'Netflix',
    skills: ['web3', 'Content Creation', 'Community'],
    job_link: 'https://jobs.netflix.com/',
  },

    {
      id: 5,
      postedOn: '2025-03-17',
      title: 'Artificial Intelligence Researcher',
      company: 'NVIDIA',
      type: 'Full Time',
      experience: 'Senior Level',
      location: 'In-office',
      skills: ['Machine Learning', 'Deep Learning', 'TensorFlow'],
      job_link: 'https://www.nvidia.com/en-us/about-nvidia/careers/',
    },
    {
      id: 6,
      postedOn: '2025-03-15',
      title: 'Cloud Solutions Architect',
      company: 'Google Cloud',
      type: 'Full Time',
      experience: 'Senior Level',
      location: 'Remote',
      skills: ['AWS', 'GCP', 'Azure'],
      job_link: 'https://cloud.google.com/careers',
    },
    {
      id: 7,
      postedOn: '2025-01-18',
      title: 'Front-End Developer',
      company: 'Snapchat',
      type: 'Part Time',
      experience: 'Mid Level',
      location: 'Hybrid',
      skills: ['React', 'HTML', 'CSS'],
      job_link: 'https://www.snapchat.com/careers',
    },
    {
      id: 8,
      postedOn: '2025-02-25',
      title: 'Product Designer',
      company: 'Dropbox',
      type: 'Full Time',
      experience: 'Senior Level',
      location: 'Remote',
      skills: ['UI/UX', 'Prototyping', 'Wireframes'],
      job_link: 'https://www.dropbox.com/careers',
    },
    {
      id: 9,
      postedOn: '2025-02-12',
      title: 'Marketing Specialist',
      company: 'HubSpot',
      type: 'Full Time',
      experience: 'Mid Level',
      location: 'Hybrid',
      skills: ['SEO', 'PPC', 'Digital Marketing'],
      job_link: 'https://www.hubspot.com/careers',
    },
    {
      id: 10,
      postedOn: '2025-03-10',
      title: 'Content Writer',
      company: 'Medium',
      type: 'Full Time',
      experience: 'Fresher',
      location: 'Remote',
      skills: ['Content Creation', 'SEO', 'Storytelling'],
      job_link: 'https://medium.com/careers',
    },
    {
      id: 11,
      postedOn: '2025-03-03',
      title: 'HR Manager',
      company: 'Twitter',
      type: 'Contract',
      experience: 'Senior Level',
      location: 'In-office',
      skills: ['HRIS', 'Recruitment', 'Employee Relations'],
      job_link: 'https://careers.twitter.com/',
    },
    {
      id: 12,
      postedOn: '2025-02-18',
      title: 'Business Intelligence Analyst',
      company: 'Uber',
      type: 'Full Time',
      experience: 'Junior Level',
      location: 'Hybrid',
      skills: ['SQL', 'Tableau', 'Power BI'],
      job_link: 'https://www.uber.com/careers',
    },
    {
      id: 13,
      postedOn: '2025-02-08',
      title: 'Quality Assurance Engineer',
      company: 'Spotify',
      type: 'Part time',
      experience: 'Mid Level',
      location: 'Remote',
      skills: ['Automation', 'Selenium', 'TestNG'],
      job_link: 'https://www.spotify.com/careers',
    },
    {
      id: 14,
      postedOn: '2025-03-01',
      title: 'Business Analyst',
      company: 'Accenture',
      type: 'Full Time',
      experience: 'Fresher',
      location: 'In-office',
      skills: ['Business Analysis', 'Data Analytics', 'Excel'],
      job_link: 'https://www.accenture.com/careers',
    },
    {
      id: 15,
      postedOn: '2025-02-11',
      title: 'Blockchain Developer',
      company: 'Coinbase',
      type: 'Contract',
      experience: 'Senior Level',
      location: 'Remote',
      skills: ['Solidity', 'Ethereum', 'Smart Contracts'],
      job_link: 'https://www.coinbase.com/careers',
    },
    {
      id: 16,
      postedOn: '2025-01-13',
      title: 'Game Developer',
      company: 'Epic Games',
      type: 'Full Time',
      experience: 'Mid Level',
      location: 'In-office',
      skills: ['Unreal Engine', 'C++', 'Game Design'],
      job_link: 'https://www.epicgames.com/careers',
    },
    {
      id: 17,
      postedOn: '2025-01-10',
      title: 'Data Engineer',
      company: 'Pinterest',
      type: 'Full Time',
      experience: 'Senior Level',
      location: 'Remote',
      skills: ['Python', 'SQL', 'Apache Hadoop'],
      job_link: 'https://www.pinterest.com/careers',
    },
    {
      id: 18,
      postedOn: '2025-02-05',
      title: 'Network Engineer',
      company: 'Oracle',
      type: 'Contract',
      experience: 'Junior Level',
      location: 'In-office',
      skills: ['Cisco', 'Networking', 'Routing'],
      job_link: 'https://www.oracle.com/careers',
    },
    {
      id: 19,
      postedOn: '2025-01-25',
      title: 'Software Engineer',
      company: 'Airbnb',
      type: 'Full Time',
      experience: 'Mid Level',
      location: 'Hybrid',
      skills: ['Ruby on Rails', 'JavaScript', 'AWS'],
      job_link: 'https://www.airbnb.com/careers',
    },
    {
      id: 20,
      postedOn: '2025-03-12',
      title: 'Product Manager',
      company: 'Slack',
      type: 'Full Time',
      experience: 'Mid Level',
      location: 'Remote',
      skills: ['Product Roadmap', 'Agile', 'Stakeholder Management'],
      job_link: 'https://slack.com/careers',
    },
    {
      id: 21,
      postedOn: '2025-03-08',
      title: 'DevOps Engineer',
      company: 'RedHat',
      type: 'Full Time',
      experience: 'Senior Level',
      location: 'Hybrid',
      skills: ['Kubernetes', 'Docker', 'CI/CD'],
      job_link: 'https://www.redhat.com/careers',
    },
    {
      id: 22,
      postedOn: '2025-02-18',
      title: 'Security Engineer',
      company: 'Cisco',
      type: 'Contract',
      experience: 'Junior Level',
      location: 'Remote',
      skills: ['Cybersecurity', 'Firewall', 'Penetration Testing'],
      job_link: 'https://www.cisco.com/careers',
    },
    {
      id: 23,
      postedOn: '2025-02-20',
      title: 'Full Stack Developer',
      company: 'IBM',
      type: 'Full Time',
      experience: 'Mid Level',
      location: 'In-office',
      skills: ['Node.js', 'React', 'MongoDB'],
      job_link: 'https://www.ibm.com/careers',
    },
    {
      id: 24,
      postedOn: '2025-01-30',
      title: 'Cloud Engineer',
      company: 'AWS',
      type: 'Full Time',
      experience: 'Senior Level',
      location: 'Remote',
      skills: ['AWS', 'Terraform', 'Docker'],
      job_link: 'https://aws.amazon.com/careers/',
    },
    {
      id: 25,
      postedOn: '2025-02-22',
      title: 'Web Developer',
      company: 'Spotify',
      type: 'Part time',
      experience: 'Fresher',
      location: 'Remote',
      skills: ['HTML', 'CSS', 'React'],
      job_link: 'https://www.spotify.com/careers',
    },
    {
      id: 26,
      postedOn: '2025-01-15',
      title: 'UX/UI Designer',
      company: 'Adobe',
      type: 'Full Time',
      experience: 'Mid Level',
      location: 'Hybrid',
      skills: ['Figma', 'Sketch', 'Wireframing'],
      job_link: 'https://www.adobe.com/careers/',
    },
    {
      id: 27,
      postedOn: '2025-02-28',
      title: 'Data Scientist',
      company: 'Tesla',
      type: 'Contract',
      experience: 'Junior Level',
      location: 'Remote',
      skills: ['Python', 'Data Analysis', 'SQL'],
      job_link: 'https://www.tesla.com/careers',
    },
    {
      id: 28,
      postedOn: '2025-03-05',
      title: 'Machine Learning Engineer',
      company: 'Microsoft',
      type: 'Full Time',
      experience: 'Senior Level',
      location: 'In-office',
      skills: ['Python', 'TensorFlow', 'Keras'],
      job_link: 'https://careers.microsoft.com/',
    },
   
]